import type { PortfolioItem } from '@/data/site'

export const seedPortfolioItems: PortfolioItem[] = [
  {
    id: 'ottoman-wars',
    title: 'Ottoman Wars',
    subtitle: 'Cinematic Ad Video',
    videoId: 'dQw4w9WgXcQ',
    category: 'ai-trailers',
    badge: 'AI Trailer',
    duration: '0:29',
    resolution: '4K',
    featured: true,
    aspectRatio: '16:9',
  },
  {
    id: 'soccer-all-stars',
    title: 'Soccer All Stars',
    subtitle: 'Gameplay Ad',
    videoId: 'dQw4w9WgXcQ',
    category: 'ai-gameplay',
    badge: 'AI + Gameplay',
    duration: '0:24',
    resolution: '4K',
    featured: true,
    aspectRatio: '16:9',
  },
  {
    id: 'ugc-style-ad',
    title: 'UGC Style Ad',
    subtitle: 'Testimonial Concept',
    videoId: 'dQw4w9WgXcQ',
    category: 'ugc-ai-ads',
    badge: 'UGC',
    duration: '0:31',
    resolution: 'HD',
    featured: true,
    aspectRatio: '16:9',
  },
  {
    id: 'game-promo-visual',
    title: 'Game Promo Visual',
    subtitle: 'Key Art & Screens',
    videoId: 'dQw4w9WgXcQ',
    category: 'promo-visuals',
    badge: 'Promo Visual',
    duration: '—',
    resolution: '4K',
    featured: true,
    aspectRatio: '16:9',
  },
  {
    id: 'youtube-shorts-cover',
    title: 'YouTube Shorts Cover',
    subtitle: 'Thumbnail Design',
    videoId: 'dQw4w9WgXcQ',
    category: 'promo-visuals',
    badge: 'Promo Visual',
    duration: '—',
    resolution: '4K',
    featured: true,
    aspectRatio: '16:9',
  },
  {
    id: 'castle-siege',
    title: 'Castle Siege',
    subtitle: 'AI Trailer Concept',
    videoId: 'dQw4w9WgXcQ',
    category: 'ai-trailers',
    badge: 'AI Trailer',
    duration: '0:35',
    resolution: '4K',
    featured: false,
    aspectRatio: '16:9',
  },
  {
    id: 'racing-rivals',
    title: 'Racing Rivals',
    subtitle: 'AI + Gameplay Mix',
    videoId: 'dQw4w9WgXcQ',
    category: 'ai-gameplay',
    badge: 'AI + Gameplay',
    duration: '0:22',
    resolution: '4K',
    featured: false,
    aspectRatio: '16:9',
  },
  {
    id: 'fantasy-quest-ugc',
    title: 'Fantasy Quest',
    subtitle: 'UGC Testimonial',
    videoId: 'dQw4w9WgXcQ',
    category: 'ugc-ai-ads',
    badge: 'UGC',
    duration: '0:28',
    resolution: 'HD',
    featured: false,
    aspectRatio: '16:9',
  },
  {
    id: 'space-commander',
    title: 'Space Commander',
    subtitle: 'Cinematic AI Trailer',
    videoId: 'dQw4w9WgXcQ',
    category: 'ai-trailers',
    badge: 'AI Trailer',
    duration: '0:41',
    resolution: '4K',
    featured: false,
    aspectRatio: '16:9',
  },
  {
    id: 'puzzle-mania',
    title: 'Puzzle Mania',
    subtitle: 'Gameplay Highlights',
    videoId: 'dQw4w9WgXcQ',
    category: 'ai-gameplay',
    badge: 'AI + Gameplay',
    duration: '0:18',
    resolution: '4K',
    featured: false,
    aspectRatio: '16:9',
  },
  {
    id: 'hero-banner-set',
    title: 'Hero Banner Set',
    subtitle: 'Store & Social Assets',
    videoId: 'dQw4w9WgXcQ',
    category: 'promo-visuals',
    badge: 'Promo Visual',
    duration: '—',
    resolution: '4K',
    featured: false,
    aspectRatio: '16:9',
  },
  {
    id: 'mobile-rpg-ugc',
    title: 'Mobile RPG',
    subtitle: 'Creator-Style Ad',
    videoId: 'dQw4w9WgXcQ',
    category: 'ugc-ai-ads',
    badge: 'UGC',
    duration: '0:33',
    resolution: 'HD',
    featured: false,
    aspectRatio: '16:9',
  },
]
